d /etc/openbao-kms 0750 root root -
d /etc/openbao-kms/tls 0755 root root -
d /var/lib/openbao-kms 0750 openbao-kms openbao-kms -
d /var/lib/openbao-kms/state 0750 openbao-kms openbao-kms -
d /run/openbao-kms 2770 openbao-kms openbao-kms-socket -
