package scaffold

import (
	_ "embed"
	"errors"
	"net"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/dc-tec/openbao-kubernetes-kms/internal/config"
)

// Deployment models the node setup script supports.
const (
	NodeModelSystemd   = "systemd"
	NodeModelStaticPod = "static-pod"
)

const (
	// The packaged systemd unit may write only these directories.
	systemdRunDir   = "/run/openbao-kms"
	systemdStateDir = "/var/lib/openbao-kms/state"
	systemdUnit     = "bao-kms-provider.service"
	systemdUser     = "openbao-kms"
	socketGroupName = "openbao-kms-socket"
	hostBinaryPath  = "/usr/bin/bao-kms-provider"

	staticPodManifestDir  = "/etc/kubernetes/manifests"
	staticPodTmpfilesPath = "/etc/tmpfiles.d/openbao-kms-static-pod.conf"

	// The check marker binds start to a recent check of the same identity.
	nodeSetupMarkerPath    = "/etc/openbao-kms/.node-setup-check"
	nodeSetupCheckMaxAge   = 3600
	nodeSetupReadyAttempts = 60
)

// nodeSetupHelpers holds the shell functions every generated script shares.
//
//go:embed nodescript_helpers.sh
var nodeSetupHelpers string

// NodeSetupOptions are the node-local values of the node setup script.
type NodeSetupOptions struct {
	// Model is NodeModelSystemd or NodeModelStaticPod.
	Model string
	// Fingerprint is the identity fingerprint of the generated configuration.
	Fingerprint string
	// ConfigFile and ManifestFile name the generated files next to the script.
	ConfigFile   string
	ManifestFile string
	// Image and SocketGID apply to static pods and match the generated manifest.
	Image     string
	SocketGID int64
}

type nodeDir struct {
	path, owner, group, mode string
	// strict directories must match owner, group, and mode exactly.
	strict bool
}

type nodeFile struct {
	flag, path, owner, group, mode string
}

type nodeLayout struct {
	runtimeGroup string
	runAs        string
	tools        []string
	dirs         []nodeDir
	files        []nodeFile
	readyURL     string
	probeHint    string
}

// RenderNodeSetup renders the POSIX shell script that prepares one
// control-plane node, installs its files, checks it as the runtime identity,
// and starts the provider. Credentials are passed when the script runs and are
// never part of the generated output.
func RenderNodeSetup(cfg config.Config, opts NodeSetupOptions) ([]byte, error) {
	layout, err := buildNodeLayout(cfg, opts)
	if err != nil {
		return nil, err
	}
	var script scriptBuilder
	script.raw("#!/bin/sh")
	script.comment("Generated by bao-kms-provider init. Review before running as root on the control-plane node.")
	script.comment("Run one phase at a time: prepare, install, check, start. Only start activates the provider.")
	script.raw("set -eu")
	script.raw(`here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)`)
	script.command(assign("model", opts.Model))
	script.command(assign("fingerprint", opts.Fingerprint))
	script.command(assign("config_target", ProviderConfigPath))
	script.command(assign("marker", nodeSetupMarkerPath))
	script.command(assign("binary", hostBinaryPath))
	script.command(assign("ready_url", layout.readyURL))
	script.command(assign("install_usage", installUsage(layout)))
	script.raw("ready_attempts=" + strconv.Itoa(nodeSetupReadyAttempts))
	script.raw("check_max_age=" + strconv.Itoa(nodeSetupCheckMaxAge))
	script.raw(`as_runtime() { ` + layout.runAs + ` "$@"; }`)
	script.blank()
	script.out.WriteString(nodeSetupHelpers)
	writePreparePhase(&script, cfg, opts, layout)
	writeInstallPhase(&script, opts, layout)
	writeCheckPhase(&script)
	writeStartPhase(&script, opts, layout)
	writeDispatch(&script)
	return []byte(script.String()), nil
}

func buildNodeLayout(cfg config.Config, opts NodeSetupOptions) (nodeLayout, error) {
	if cfg.Auth.Method != config.AuthMethodJWT {
		return nodeLayout{}, errors.New("node setup supports JWT auth only; install certificate auth material by hand")
	}
	if opts.Fingerprint == "" || opts.ConfigFile == "" {
		return nodeLayout{}, errors.New("node setup needs the identity fingerprint and the generated configuration file")
	}
	readyURL, err := nodeReadyURL(cfg.Server.HealthAddress)
	if err != nil {
		return nodeLayout{}, err
	}
	layout, err := modelLayout(cfg, opts)
	if err != nil {
		return nodeLayout{}, err
	}
	layout.readyURL = readyURL
	addCredentialLayout(&layout, cfg)
	layout.dirs = uniqueNodeDirs(layout.dirs)
	return layout, nil
}

func modelLayout(cfg config.Config, opts NodeSetupOptions) (nodeLayout, error) {
	runDir := filepath.Dir(cfg.Server.SocketPath)
	stateDir := filepath.Dir(cfg.State.Path)
	common := []string{"id", "install", "stat", "getent", "cut", "grep", "date", "mkdir", "dirname", "setpriv", "curl"}
	switch opts.Model {
	case NodeModelSystemd:
		if runDir != systemdRunDir || stateDir != systemdStateDir {
			return nodeLayout{}, errors.New("the packaged systemd unit writes only " + systemdRunDir + " and " +
				systemdStateDir + "; keep server.socketPath and state.path in those directories")
		}
		return nodeLayout{
			runtimeGroup: systemdUser,
			runAs:        "setpriv --reuid=" + systemdUser + " --regid=" + systemdUser + " --init-groups --",
			tools:        append(common, "systemctl"),
			probeHint:    "sh /usr/share/bao-kms-provider/probe-apiserver",
		}, nil
	case NodeModelStaticPod:
		if err := ValidateImageDigest(opts.Image); err != nil {
			return nodeLayout{}, err
		}
		if opts.SocketGID <= 0 || opts.ManifestFile == "" {
			return nodeLayout{}, errors.New("static pod node setup needs the socket GID and the generated manifest")
		}
		if err := validateStaticPodDirectories(cfg, runDir, stateDir); err != nil {
			return nodeLayout{}, err
		}
		uid := strconv.Itoa(ContainerUID)
		return nodeLayout{
			runtimeGroup: uid,
			runAs: "setpriv --reuid=" + uid + " --regid=" + uid +
				" --groups=" + strconv.FormatInt(opts.SocketGID, 10) + " --",
			tools:     append(common, "systemd-tmpfiles", "crictl", "cmp", "cat", "chmod"),
			probeHint: "sh bin/probe-apiserver (from the static-pod kit)",
			dirs: []nodeDir{
				{path: filepath.Dir(ProviderConfigPath), owner: "root", group: uid, mode: "750"},
				{path: stateDir, owner: uid, group: uid, mode: "750", strict: true},
			},
		}, nil
	default:
		return nodeLayout{}, errors.New("node setup model must be systemd or static-pod")
	}
}

func addCredentialLayout(layout *nodeLayout, cfg config.Config) {
	credentialPath := cfg.Auth.JWT.JWTFile
	if cfg.Auth.JWT.Source == config.JWTSourceOAuth2 {
		credentialPath = cfg.Auth.JWT.OAuth2.ClientSecretFile
	}
	layout.dirs = append(layout.dirs,
		nodeDir{path: filepath.Dir(cfg.OpenBao.CACertFile), owner: "root", group: "root", mode: "755"},
		nodeDir{path: filepath.Dir(credentialPath), owner: "root", group: layout.runtimeGroup, mode: "750"})
	layout.files = []nodeFile{
		{flag: "--ca", path: cfg.OpenBao.CACertFile, owner: "root", group: "root", mode: "644"},
		{flag: "--credential", path: credentialPath, owner: "root", group: layout.runtimeGroup, mode: "640"},
	}
	if cfg.Auth.JWT.Source == config.JWTSourceOAuth2 && cfg.Auth.JWT.OAuth2.CACertFile != "" {
		issuerCA := cfg.Auth.JWT.OAuth2.CACertFile
		layout.dirs = append(layout.dirs, nodeDir{path: filepath.Dir(issuerCA), owner: "root", group: "root", mode: "755"})
		layout.files = append(layout.files,
			nodeFile{flag: "--issuer-ca", path: issuerCA, owner: "root", group: "root", mode: "644"})
	}
}

// uniqueNodeDirs keeps the first entry for each path, so a shared directory is
// prepared once with the stricter owner that was listed first.
func uniqueNodeDirs(dirs []nodeDir) []nodeDir {
	seen := make(map[string]bool, len(dirs))
	unique := dirs[:0]
	for _, dir := range dirs {
		if seen[dir.path] {
			continue
		}
		seen[dir.path] = true
		unique = append(unique, dir)
	}
	return unique
}

func nodeReadyURL(address string) (string, error) {
	port, err := addressPort(address)
	if err != nil {
		return "", errors.New("server.healthAddress: " + err.Error())
	}
	return "http://" + net.JoinHostPort(probeHost(address), strconv.Itoa(port)) + "/ready", nil
}

func installUsage(layout nodeLayout) string {
	parts := make([]string, 0, len(layout.files))
	for _, file := range layout.files {
		parts = append(parts, file.flag+" <file>")
	}
	return strings.Join(parts, " ")
}

func writePreparePhase(script *scriptBuilder, cfg config.Config, opts NodeSetupOptions, layout nodeLayout) {
	script.raw(`phase_prepare() {`)
	script.raw(`  require_root`)
	script.raw(`  require_tools ` + strings.Join(layout.tools, " "))
	script.raw(`  [ -x "$binary" ] || fail 3 "$binary is missing; install the release artifact first"`)
	switch opts.Model {
	case NodeModelSystemd:
		writeSystemdPrepare(script)
	case NodeModelStaticPod:
		writeStaticPodPrepare(script, cfg, opts)
	}
	for _, dir := range layout.dirs {
		words := []shellWord{lit("  ensure_dir"), val(dir.path), val(dir.owner), val(dir.group), lit(dir.mode)}
		if dir.strict {
			words = append(words, lit("strict"))
		}
		script.command(words...)
	}
	script.raw(`  say "Next: sh $0 install $install_usage"`)
	script.raw(`}`)
	script.blank()
}

func writeSystemdPrepare(script *scriptBuilder) {
	missing := func(what string) string { return "fail 3 '" + what + " is missing; install the package or tarball'" }
	script.raw(`  unit_found=''`)
	script.raw(`  for dir in /etc/systemd/system /usr/lib/systemd/system /lib/systemd/system; do`)
	script.raw(`    [ ! -f "$dir/` + systemdUnit + `" ] || unit_found=yes`)
	script.raw(`  done`)
	script.raw(`  [ -n "$unit_found" ] || ` + missing("the "+systemdUnit+" unit"))
	script.raw(`  getent passwd ` + systemdUser + ` >/dev/null || ` + missing("user "+systemdUser))
	script.raw(`  getent group ` + socketGroupName + ` >/dev/null || ` + missing("group "+socketGroupName))
	script.raw(`  [ -d ` + systemdRunDir + ` ] ||`)
	script.raw(`    fail 3 '` + systemdRunDir + ` is missing; run systemd-tmpfiles --create'`)
}

func writeStaticPodPrepare(script *scriptBuilder, cfg config.Config, opts NodeSetupOptions) {
	gid := strconv.FormatInt(opts.SocketGID, 10)
	uid := strconv.Itoa(ContainerUID)
	runDir := filepath.Dir(cfg.Server.SocketPath)
	regenerate := "bao-kms-provider init --values generated/config.yaml --out <dir> --model static-pod" +
		" --image " + opts.Image + " --socket-gid $gid"
	script.raw(`  gid=$(getent group ` + socketGroupName + ` | cut -d: -f3)`)
	script.raw(`  [ -n "$gid" ] || fail 3 'group ` + socketGroupName + ` is missing; run groupadd --system ` +
		socketGroupName + `'`)
	script.raw(`  [ "$gid" = ` + shellQuote(gid) + ` ] ||`)
	script.raw(`    fail 3 "this node's ` + socketGroupName + ` GID is $gid, but these files are for ` + gid +
		`; generate this node's files with: ` + regenerate + `"`)
	script.raw(`  [ -d ` + staticPodManifestDir + ` ] || fail 3 '` + staticPodManifestDir +
		` is missing; this model needs the kubelet static pod path'`)
	script.command(lit("  crictl inspecti"), val(opts.Image), lit(">/dev/null 2>&1 ||"))
	preload := "the provider image is not preloaded; verify it, then run: crictl pull " + opts.Image
	script.command(lit("    fail 3"), val(preload))
	script.command(lit("  line=" + shellQuote("d "+runDir+" 2750 "+uid+" "+gid+" -")))
	script.raw(`  tmpfiles=` + staticPodTmpfilesPath)
	script.raw(`  if [ -e "$tmpfiles" ]; then`)
	script.raw(`    [ "$(cat "$tmpfiles")" = "$line" ] || fail 3 "$tmpfiles differs from this generation"`)
	script.raw(`  else`)
	script.raw(`    printf '%s\n' "$line" > "$tmpfiles"`)
	script.raw(`    chmod 644 "$tmpfiles"`)
	script.raw(`    say "created $tmpfiles"`)
	script.raw(`  fi`)
	script.raw(`  systemd-tmpfiles --create "$tmpfiles"`)
	script.command(lit("  ensure_dir"), val(runDir), lit(uid), lit(gid), lit("2750 strict"))
}

func writeInstallPhase(script *scriptBuilder, opts NodeSetupOptions, layout nodeLayout) {
	script.raw(`phase_install() {`)
	script.raw(`  require_root`)
	for index := range layout.files {
		script.raw(`  file` + strconv.Itoa(index) + `=''`)
	}
	script.raw(`  while [ "$#" -gt 0 ]; do`)
	script.raw(`    [ "$#" -ge 2 ] || fail 2 "$1 needs a file argument"`)
	script.raw(`    case $1 in`)
	for index, file := range layout.files {
		script.raw(`      ` + file.flag + `) file` + strconv.Itoa(index) + `=$2 ;;`)
	}
	script.raw(`      *) fail 2 "unknown install argument $1; expected $install_usage" ;;`)
	script.raw(`    esac`)
	script.raw(`    shift 2`)
	script.raw(`  done`)
	for index, file := range layout.files {
		script.raw(`  [ -n "$file` + strconv.Itoa(index) + `" ] || fail 2 '` + file.flag + ` <file> is required'`)
	}
	script.command(lit(`  install_new "$here"/`+shellQuote(opts.ConfigFile)), lit(`"$config_target"`),
		lit("root"), val(layout.runtimeGroup), lit("640"))
	for index, file := range layout.files {
		script.command(lit(`  install_new "$file`+strconv.Itoa(index)+`"`), val(file.path),
			val(file.owner), val(file.group), lit(file.mode))
	}
	script.raw(`  say "Next: sh $0 check"`)
	script.raw(`}`)
	script.blank()
}

func writeCheckPhase(script *scriptBuilder) {
	script.raw(`phase_check() {`)
	script.raw(`  require_root`)
	script.raw(`  run_checks`)
	script.raw(`  say "Next: sh $0 start"`)
	script.raw(`}`)
	script.blank()
}

func writeStartPhase(script *scriptBuilder, opts NodeSetupOptions, layout nodeLayout) {
	script.raw(`phase_start() {`)
	script.raw(`  require_root`)
	script.raw(`  require_recent_check`)
	switch opts.Model {
	case NodeModelSystemd:
		script.raw(`  systemctl enable --now ` + systemdUnit)
		script.raw(`  say 'enabled and started ` + systemdUnit + `'`)
	case NodeModelStaticPod:
		source := `"$here"/` + shellQuote(opts.ManifestFile)
		script.command(assign("  manifest", filepath.Join(staticPodManifestDir, opts.ManifestFile)))
		script.raw(`  if [ -e "$manifest" ]; then`)
		script.raw(`    cmp -s ` + source + ` "$manifest" || fail 3 "$manifest differs from this generation"`)
		script.raw(`  else`)
		script.raw(`    install -o root -g root -m 644 -- ` + source + ` "$manifest"`)
		script.raw(`    say "installed $manifest"`)
		script.raw(`  fi`)
	}
	script.raw(`  wait_ready`)
	script.raw(`  say 'After the local kube-apiserver uses the socket, check its access with:'`)
	script.raw(`  say '  ` + layout.probeHint + `'`)
	script.raw(`  say 'Next, once every control-plane node is ready:'`)
	script.raw(`  say '  stage encryption-config-readers.yaml (Enable encryption, Step 1)'`)
	script.raw(`}`)
	script.blank()
}

func writeDispatch(script *scriptBuilder) {
	script.raw(`phase=${1:-}`)
	script.raw(`[ "$#" -eq 0 ] || shift`)
	script.raw(`case $phase in`)
	script.raw(`  '') usage ;;`)
	script.raw(`  install) phase_install "$@" ;;`)
	script.raw(`  prepare | check | start)`)
	script.raw(`    [ "$#" -eq 0 ] || fail 2 "$phase takes no arguments"`)
	script.raw(`    "phase_$phase" ;;`)
	script.raw(`  *) usage >&2; exit 2 ;;`)
	script.raw(`esac`)
}
