package scaffold

import (
	"errors"
	"strings"

	"github.com/dc-tec/openbao-kubernetes-kms/internal/config"
)

const (
	// PolicyFileName is the policy file the setup script applies.
	PolicyFileName = "openbao-policy.hcl"
	authPathPrefix = "auth/"
	jwtTokenTTL    = "30m"
	jwtTokenMaxTTL = "1h"
)

// SetupOptions are OpenBao-side values that are not part of the provider configuration.
type SetupOptions struct {
	// PolicyName names the OpenBao policy attached to the auth role.
	PolicyName string
}

// ValidateSetup checks that the configuration carries everything the setup
// script needs.
func ValidateSetup(cfg config.Config, opts SetupOptions) error {
	var problems []string
	if strings.TrimSpace(opts.PolicyName) == "" {
		problems = append(problems, "policy name must not be empty")
	}
	if cfg.Auth.Method == authMethodJWT {
		if !strings.HasPrefix(cfg.Auth.JWT.MountPath, authPathPrefix) {
			problems = append(problems, "auth.jwt.mountPath must start with auth/")
		}
		if cfg.Auth.JWT.ExpectedIssuer == "" {
			problems = append(problems, "auth.jwt.expectedIssuer is required to configure the OpenBao JWT auth mount")
		}
		if len(cfg.Auth.JWT.ExpectedAudience) == 0 {
			problems = append(problems, "auth.jwt.expectedAudience is required to bind the OpenBao JWT role")
		}
		if cfg.Auth.JWT.ExpectedSubject == "" {
			problems = append(problems, "auth.jwt.expectedSubject is required to bind the OpenBao JWT role")
		}
	}
	if len(problems) > 0 {
		return errors.New(strings.Join(problems, "; "))
	}
	return nil
}

// RenderOpenBaoSetup renders a POSIX shell script with the bao commands that
// prepare OpenBao for this configuration. An administrator reviews and runs
// it; the provider never calls these endpoints.
func RenderOpenBaoSetup(cfg config.Config, opts SetupOptions) ([]byte, error) {
	if err := ValidateSetup(cfg, opts); err != nil {
		return nil, err
	}
	var script scriptBuilder
	script.raw("#!/bin/sh")
	script.comment("Generated by bao-kms-provider init. Review, then run once as an OpenBao administrator.")
	script.comment("Requires the bao CLI, logged in with a token that can manage mounts, auth, and policies.")
	script.raw("set -eu")
	script.raw(`policy_file="$(dirname "$0")/` + PolicyFileName + `"`)
	script.blank()
	if cfg.OpenBao.Namespace != "" {
		script.command(lit("export"), assign("BAO_NAMESPACE", cfg.OpenBao.Namespace))
		script.blank()
	}

	script.comment("Dedicated Transit mount. disable_upsert stops encrypt calls from creating keys.")
	script.command(lit("bao"), lit("secrets"), lit("enable"), flag("-path", cfg.Transit.MountPath), lit("transit"))
	script.command(lit("bao"), lit("write"), val(cfg.Transit.MountPath+"/config/keys"), lit("disable_upsert=true"))
	script.blank()

	script.comment("Transit key. Never enable exportable or allow_plaintext_backup: OpenBao cannot revert them.")
	script.comment("Its key lineage ID is " + cfg.Transit.KeyIDScope.KeyLineageID + "; a recreated key needs a new one.")
	script.command(lit("bao"), lit("write"), val(cfg.Transit.MountPath+"/keys/"+cfg.Transit.KeyName),
		lit("type=aes256-gcm96"), lit("exportable=false"), lit("allow_plaintext_backup=false"))
	script.blank()

	script.comment("Least-privilege policy for the provider token.")
	script.command(lit("bao"), lit("policy"), lit("write"), val(opts.PolicyName), lit(`"$policy_file"`))
	script.blank()

	switch cfg.Auth.Method {
	case authMethodJWT:
		mountPath := cfg.Auth.JWT.MountPath
		script.comment("JWT auth through OIDC discovery on the provider's issuer. The issuer must stay")
		script.comment("reachable when the protected API server is down.")
		script.command(lit("bao"), lit("auth"), lit("enable"),
			flag("-path", strings.TrimPrefix(mountPath, authPathPrefix)), lit("jwt"))
		script.command(lit("bao"), lit("write"), val(mountPath+"/config"),
			assign("oidc_discovery_url", cfg.Auth.JWT.ExpectedIssuer),
			assign("bound_issuer", cfg.Auth.JWT.ExpectedIssuer))
		script.command(lit("bao"), lit("write"), val(mountPath+"/role/"+cfg.Auth.JWT.Role),
			lit("role_type=jwt"),
			assign("bound_audiences", strings.Join(cfg.Auth.JWT.ExpectedAudience, ",")),
			assign("bound_subject", cfg.Auth.JWT.ExpectedSubject),
			lit("user_claim=sub"),
			assign("token_policies", opts.PolicyName),
			lit("token_ttl="+jwtTokenTTL),
			lit("token_max_ttl="+jwtTokenMaxTTL),
			lit("token_no_default_policy=true"))
	case authMethodCert:
		script.comment("Certificate auth: create the cert auth mount and a role bound to the provider")
		script.comment("certificate identity, attaching the policy above. See Configure: OpenBao auth and policy.")
	}
	return []byte(script.String()), nil
}

// shellWord is one word of a generated shell command.
type shellWord struct {
	text string
}

// lit is a word the generator controls; it is written as is.
func lit(text string) shellWord { return shellWord{text: text} }

// val is a configuration value; it is always quoted.
func val(value string) shellWord { return shellWord{text: shellQuote(value)} }

// assign renders key=value with the value quoted.
func assign(key string, value string) shellWord {
	return shellWord{text: key + "=" + shellQuote(value)}
}

// flag renders -name=value with the value quoted.
func flag(name string, value string) shellWord {
	return shellWord{text: name + "=" + shellQuote(value)}
}

type scriptBuilder struct {
	out strings.Builder
}

func (b *scriptBuilder) raw(line string) {
	b.out.WriteString(line)
	b.out.WriteString("\n")
}

func (b *scriptBuilder) blank() { b.out.WriteString("\n") }

func (b *scriptBuilder) comment(text string) { b.raw("# " + text) }

func (b *scriptBuilder) command(words ...shellWord) {
	parts := make([]string, len(words))
	for index, word := range words {
		parts[index] = word.text
	}
	b.raw(strings.Join(parts, " "))
}

func (b *scriptBuilder) String() string { return b.out.String() }

// shellQuote returns s as one single-quoted POSIX shell word.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
